# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

import("./Fastlane_config")

platform :ios do
  desc "Run tests"
  lane :test do
    run_tests(
      workspace: Config::WORKSPACE,
      devices: Config::TEST_DEVICES,
      scheme: Config::TEST_SCHEME
    )
  end

  desc "Builds xcframework for distribution"
  lane :build_xcframework do
    test
    create_xcframework(
      workspace: Config::WORKSPACE,
      scheme: Config::BUILD_SCHEME,
      product_name: Config::BUILD_SCHEME,
      destinations: Config::PLATFORMS,
      xcframework_output_directory: Config::ARCHIVE_PATH
    )
  end

  desc "Push new version to pod trunk"
  lane :release_pod do
    pod_push(path: Config::PODSPEC_FILE)
  end
end
